services:
# --MsSQL--
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: MsSQL_2
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    healthcheck:
        test: /var/opt/mssql/bin/sqlcmd -C -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
    volumes:  
      - db-data:/var/opt/mssql 
    ports:
      - "3330:1433"
# --Redis--
  redis:
    image: redis
    container_name: Redis_2
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER} 
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    volumes:
      - redis-data:/redisdata:/data
    ports:
      - "9990:6379"  
  # --Kafka--
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  # --backand--:
  backand:
    container_name: Backend
    build:
     context: ./backend
    depends_on:
       mssql:
        condition: service_healthy
  # --frontend--:
  frontend:
    container_name: Frontend
    build:
     context: ./frontend
volumes: 
  db-data:
  redis-data:
  backand-data:


# services:
#   ms-sql-server:
#     container_name: mssql
#     image: mcr.microsoft.com/mssql/server
#     environment:
#       ACCEPT_EULA: 'Y'
#       MSSQL_SA_PASSWORD: 'root'
#       MSSQL_PID: 'Developer' 
#       MSSQL_TCP_PORT: 1433 
#     ports: 
#       - "3330:1433"

